from .agent import Agent
from .random_agent import RandomAgent
from .human_agent import HumanAgent
from .student_agent import StudentAgent
from .student_agent5 import StudentAgent5
from .student_agent6 import StudentAgent6
from .student_agent7 import StudentAgent7
from .student_agent8 import StudentAgent8
from .student_agent9 import StudentAgent9
from .student_agent10 import StudentAgent10
from .student_agent11 import StudentAgent11
from .student_agent12 import StudentAgent12
from .student_agent13 import StudentAgent13
from .student_agent14 import StudentAgent14
from .student_agent15 import StudentAgent15
from .student_agent16 import StudentAgent16
from .student_agent17 import StudentAgent17
from .student_agent18 import StudentAgent18